package week4;

Public class Person {
    // this is a person class
    // this is a blueprint for a person object
    // this is a template for a person object
    public string name = "";
    public string namecatsdogs; // another way to declare a variable
    public int age = 0;
    public string favcolor = "";
    public double giftTotal = 0.0;
    public static int count = 0; // this is a class variable
    // this is a class variable because it is declared inside the class

    public person(string name) {
        this.name = name;

       // count++;
    }}

    public person(){
        name = "John Doe";
        
    }